##############################################################################
# Copyright (C) Alpha Networks 2006-2010
# All Rights Reserved -- Company Confidential
# Author: wills_yin@alphanetworks.com
# misc top-level Makefile
##############################################################################

#
# global settings section 
#

TOP        := $(shell pwd)/../..#
COMPONENT  := misc# comment to remove trailing space 

include $(TOP)/Target.mk
include $(TOP)/Target.options

#
# common rules section 
#

SUBDIRS :=
ifneq ($(CONF_DISABLE_NETMAN), y)
	SUBDIRS += netman
endif
ifneq ($(CONF_DISABLE_DNS_DAEMON), y)
	SUBDIRS += dns_daemon
endif
ifneq ($(CONF_DISABLE_DISK_MANAGER), y)
	SUBDIRS += disk_manager
endif

SUBDIRS_$(CONF_EXAMPLE_LIBHELLO)   += libhello 
SUBDIRS_$(CONF_EXAMPLE_HELLO)      += hello_test
SUBDIRS_$(CONF_CP210X_TEST)        += cp210x_test

SUBDIRS_$(CONF_IO_DAEMON)  += io_daemon
SUBDIRS_$(CONF_FIRMWARE_UPGRADING_DAEMON)  += fw_upgrader

SUBDIRS_$(CONF_USERAGENT) += channelizedengine
SUBDIRS_$(CONF_DMA_EASTFORK_DEV_CONF)  += eastfork_dev_conf 
ifeq ($(CONF_USE_CAS_2_0),y)
SUBDIRS_$(CONF_CAS) += cas2.0
else
SUBDIRS_$(CONF_CAS) += cas
endif
SUBDIRS_$(CONF_DMA_DEBUG_SYSTEM) += log
SUBDIRS_$(CONF_MEDIA_SERVER) += media_server
SUBDIRS_$(CONF_SAMBA) += samba
SUBDIRS_$(CONF_DMA_YOUTUBE) += youtube
SUBDIRS_$(CONF_VOOLETV) += vooletv
SUBDIRS_$(CONF_DMA_PICASA) += picasa
SUBDIRS_$(CONF_DEVICE15) += device1.5
SUBDIRS_$(CONF_DEVICE_PORTAL) += device_portal
SUBDIRS_$(CONF_SOFT_IRDA) += soft_irda
SUBDIRS_$(CONF_FLASH_GAME) += flash_game
SUBDIRS_$(CONF_DIRECTFBRC_BUILDER) += directfbrc_builder
SUBDIRS_$(CONF_HIDDEV_MANAGER) += hiddev_manager
SUBDIRS_$(CONF_IPS) += ips
SUBDIRS += $(SUBDIRS_y)

include $(TOP_SCRIPTS_DIR)/rules.mk

#
# install
#
.PHONY: install install-all

install install_all:
	for dir in $(SUBDIRS); do \
		make -C $$dir install; \
	done
