(setq perldoc-obarray (make-vector 1519 nil))
;; Functions
(mapc (lambda (func)
         (set (intern func perldoc-obarray) t))
'(
"*" "-A" "-B" "-C" "-M" "-O" "-R" "-S" "-T" "-W" "-X" "-b" "-c" "-d" "-e"
"-f" "-g" "-k" "-l" "-o" "-p" "-r" "-s" "-t" "-u" "-w" "-x" "-z"
"Otherwise," "Otherwise:" "abs" "accept" "alarm" "atan2" "bind" "binmode"
"bless" "break" "caller" "chdir" "chmod" "chomp" "chop" "chown" "chr"
"chroot" "close" "closedir" "connect" "continue" "cos" "crypt" "dbmclose"
"dbmopen" "defined" "delete" "die" "do" "dump" "each" "endgrent"
"endhostent" "endnetent" "endprotoent" "endpwent" "endservent" "eof" "eval"
"exec" "exists" "exit" "exp" "fcntl" "fileno" "flock" "fork" "format"
"formline" "getc" "getgrent" "getgrgid" "getgrnam" "gethostbyaddr"
"gethostbyname" "gethostent" "getlogin" "getnetbyaddr" "getnetbyname"
"getnetent" "getpeername" "getpgrp" "getppid" "getpriority"
"getprotobyname" "getprotobynumber" "getprotoent" "getpwent" "getpwnam"
"getpwuid" "getservbyname" "getservbyport" "getservent" "getsockname"
"getsockopt" "glob" "gmtime" "goto" "grep" "hex" "import" "index" "int"
"ioctl" "join" "keys" "kill" "last" "lc" "lcfirst" "length" "link" "listen"
"local" "localtime" "lock" "log" "lstat" "m" "map" "mkdir" "msgctl"
"msgget" "msgrcv" "msgsnd" "my" "next" "no" "oct" "open" "opendir" "ord"
"our" "pack" "package" "pipe" "pop" "pos" "print" "printf" "prototype"
"push" "q" "qq" "qr" "quotemeta" "qw" "qx" "rand" "read" "readdir"
"readline" "readlink" "readpipe" "recv" "redo" "ref" "rename" "require"
"reset" "return" "reverse" "rewinddir" "rindex" "rmdir" "s" "say" "scalar"
"seek" "seekdir" "select" "semctl" "semget" "semop" "send" "setgrent"
"sethostent" "setnetent" "setpgrp" "setpriority" "setprotoent" "setpwent"
"setservent" "setsockopt" "shift" "shmctl" "shmget" "shmread" "shmwrite"
"shutdown" "sin" "sleep" "socket" "socketpair" "sort" "splice" "split"
"sprintf" "sqrt" "srand" "stat" "state" "study" "sub" "substr" "symlink"
"syscall" "sysopen" "sysread" "sysseek" "system" "syswrite" "tell"
"telldir" "tie" "tied" "time" "times" "tr" "truncate" "uc" "ucfirst"
"umask" "undef" "unlink" "unpack" "unshift" "untie" "use" "utime" "values"
"vec" "wait" "waitpid" "wantarray" "warn" "write" "y"))

;; Modules
(mapc (lambda (mod)
         (intern mod perldoc-obarray))
'(
"APR" "APR::Base64" "APR::Brigade" "APR::Bucket" "APR::BucketAlloc"
"APR::BucketType" "APR::Const" "APR::Date" "APR::Error" "APR::Finfo"
"APR::IpSubnet" "APR::OS" "APR::PerlIO" "APR::Pool" "APR::SockAddr"
"APR::Socket" "APR::Status" "APR::String" "APR::Table" "APR::ThreadRWLock"
"APR::URI" "APR::UUID" "APR::Util" "APR::XSLoader" "AnyDBM_File"
"Apache2::Access" "Apache2::CmdParms" "Apache2::Command"
"Apache2::Connection" "Apache2::ConnectionUtil" "Apache2::Const"
"Apache2::Directive" "Apache2::Filter" "Apache2::FilterRec"
"Apache2::HookRun" "Apache2::Log" "Apache2::MPM" "Apache2::Module"
"Apache2::PerlSections" "Apache2::PerlSections::Dump" "Apache2::Process"
"Apache2::RequestIO" "Apache2::RequestRec" "Apache2::RequestUtil"
"Apache2::Resource" "Apache2::Response" "Apache2::ServerRec"
"Apache2::ServerUtil" "Apache2::SizeLimit" "Apache2::SourceTables"
"Apache2::Status" "Apache2::SubProcess" "Apache2::SubRequest"
"Apache2::URI" "Apache2::Util" "Apache2::XSLoader" "Apache2::compat"
"Apache2::porting" "App::Cpan" "App::Prove" "App::Prove::State"
"App::Prove::State::Result" "App::Prove::State::Result::Test"
"Archive::Tar" "Archive::Tar::Constant" "Archive::Tar::File" "Archive::Zip"
"Archive::Zip::Archive" "Archive::Zip::BufferedFileHandle"
"Archive::Zip::DirectoryMember" "Archive::Zip::FAQ"
"Archive::Zip::FileMember" "Archive::Zip::Member"
"Archive::Zip::MemberRead" "Archive::Zip::MockFileHandle"
"Archive::Zip::NewFileMember" "Archive::Zip::StringMember"
"Archive::Zip::Tree" "Archive::Zip::ZipFileMember" "Attribute::Handlers"
"Attribute::Params::Validate" "AutoLoader" "AutoSplit" "B" "B::Concise"
"B::Debug" "B::Deparse" "B::Lint" "B::Lint::Debug" "B::Showlex" "B::Terse"
"B::Xref" "BSD::Resource" "Benchmark" "Bundle::Apache2"
"Bundle::DBD::mysql" "Bundle::DBI" "Bundle::LWP" "CGI" "CGI::Apache"
"CGI::Carp" "CGI::Cookie" "CGI::Fast" "CGI::Pretty" "CGI::Push"
"CGI::Switch" "CGI::Util" "CORE" "CPAN" "CPAN::API::HOWTO" "CPAN::Author"
"CPAN::Bundle" "CPAN::CacheMgr" "CPAN::Complete" "CPAN::Debug"
"CPAN::DeferredCode" "CPAN::Distribution" "CPAN::Distroprefs"
"CPAN::Distrostatus" "CPAN::Exception::RecursiveDependency"
"CPAN::Exception::blocked_urllist" "CPAN::Exception::yaml_not_installed"
"CPAN::FTP" "CPAN::FTP::netrc" "CPAN::FirstTime" "CPAN::HandleConfig"
"CPAN::Index" "CPAN::InfoObj" "CPAN::Kwalify" "CPAN::LWP::UserAgent"
"CPAN::Mirrors" "CPAN::Module" "CPAN::Nox" "CPAN::Prompt" "CPAN::Queue"
"CPAN::Shell" "CPAN::Tarzip" "CPAN::URL" "CPAN::Version" "Carp"
"Carp::Heavy" "Class::Singleton" "Class::Struct" "Compress::Raw::Bzip2"
"Compress::Raw::Zlib" "Compress::Zlib" "Config" "Config::Extensions"
"Crypt::Makerand" "Crypt::OpenSSL::Bignum" "Crypt::OpenSSL::Bignum::CTX"
"Crypt::OpenSSL::RSA" "Crypt::OpenSSL::Random" "Cwd" "DB" "DBD::DBM"
"DBD::ExampleP" "DBD::File" "DBD::File::Developers" "DBD::File::Roadmap"
"DBD::Gofer" "DBD::Gofer::Policy::Base" "DBD::Gofer::Policy::classic"
"DBD::Gofer::Policy::pedantic" "DBD::Gofer::Policy::rush"
"DBD::Gofer::Transport::Base" "DBD::Gofer::Transport::null"
"DBD::Gofer::Transport::pipeone" "DBD::Gofer::Transport::stream"
"DBD::NullP" "DBD::Proxy" "DBD::Sponge" "DBD::mysql" "DBD::mysql::GetInfo"
"DBD::mysql::INSTALL" "DBI" "DBI::Changes" "DBI::Const::GetInfo::ANSI"
"DBI::Const::GetInfo::ODBC" "DBI::Const::GetInfoReturn"
"DBI::Const::GetInfoType" "DBI::DBD" "DBI::DBD::Metadata"
"DBI::DBD::SqlEngine" "DBI::FAQ" "DBI::Gofer::Execute"
"DBI::Gofer::Request" "DBI::Gofer::Response" "DBI::Gofer::Serializer::Base"
"DBI::Gofer::Serializer::DataDumper" "DBI::Gofer::Serializer::Storable"
"DBI::Gofer::Transport::Base" "DBI::Gofer::Transport::pipeone"
"DBI::Gofer::Transport::stream" "DBI::Profile" "DBI::ProfileData"
"DBI::ProfileDumper" "DBI::ProfileDumper::Apache" "DBI::ProfileSubs"
"DBI::ProxyServer" "DBI::PurePerl" "DBI::Roadmap" "DBI::SQL::Nano"
"DBI::Util::CacheMemory" "DBI::Util::_accessor" "DBM_Filter"
"DBM_Filter::compress" "DBM_Filter::encode" "DBM_Filter::int32"
"DBM_Filter::null" "DBM_Filter::utf8" "DB_File" "Data::Dumper"
"Date::Format" "Date::Language" "Date::Language::Afar"
"Date::Language::Amharic" "Date::Language::Austrian"
"Date::Language::Brazilian" "Date::Language::Chinese"
"Date::Language::Chinese_GB" "Date::Language::Czech"
"Date::Language::Danish" "Date::Language::Dutch" "Date::Language::English"
"Date::Language::Finnish" "Date::Language::French" "Date::Language::Gedeo"
"Date::Language::German" "Date::Language::Greek"
"Date::Language::Hungarian" "Date::Language::Icelandic"
"Date::Language::Italian" "Date::Language::Norwegian"
"Date::Language::Oromo" "Date::Language::Romanian"
"Date::Language::Russian" "Date::Language::Russian_cp1251"
"Date::Language::Russian_koi8r" "Date::Language::Sidama"
"Date::Language::Somali" "Date::Language::Spanish"
"Date::Language::Swedish" "Date::Language::Tigrinya"
"Date::Language::TigrinyaEritrean" "Date::Language::TigrinyaEthiopian"
"Date::Language::Turkish" "Date::Parse" "DateTime" "DateTime::Duration"
"DateTime::Format::Mail" "DateTime::Format::W3CDTF" "DateTime::Helpers"
"DateTime::Infinite" "DateTime::LeapSecond" "DateTime::Locale"
"DateTime::Locale::Base" "DateTime::Locale::Catalog" "DateTime::Locale::aa"
"DateTime::Locale::aa_DJ" "DateTime::Locale::aa_ER"
"DateTime::Locale::aa_ER_SAAHO" "DateTime::Locale::aa_ET"
"DateTime::Locale::af" "DateTime::Locale::af_NA" "DateTime::Locale::af_ZA"
"DateTime::Locale::ak" "DateTime::Locale::ak_GH" "DateTime::Locale::am"
"DateTime::Locale::am_ET" "DateTime::Locale::ar" "DateTime::Locale::ar_AE"
"DateTime::Locale::ar_BH" "DateTime::Locale::ar_DZ"
"DateTime::Locale::ar_EG" "DateTime::Locale::ar_IQ"
"DateTime::Locale::ar_JO" "DateTime::Locale::ar_KW"
"DateTime::Locale::ar_LB" "DateTime::Locale::ar_LY"
"DateTime::Locale::ar_MA" "DateTime::Locale::ar_OM"
"DateTime::Locale::ar_QA" "DateTime::Locale::ar_SA"
"DateTime::Locale::ar_SD" "DateTime::Locale::ar_SY"
"DateTime::Locale::ar_TN" "DateTime::Locale::ar_YE" "DateTime::Locale::as"
"DateTime::Locale::as_IN" "DateTime::Locale::az" "DateTime::Locale::az_AZ"
"DateTime::Locale::az_Cyrl" "DateTime::Locale::az_Cyrl_AZ"
"DateTime::Locale::az_Latn" "DateTime::Locale::az_Latn_AZ"
"DateTime::Locale::be" "DateTime::Locale::be_BY" "DateTime::Locale::bg"
"DateTime::Locale::bg_BG" "DateTime::Locale::bn" "DateTime::Locale::bn_BD"
"DateTime::Locale::bn_IN" "DateTime::Locale::bo" "DateTime::Locale::bo_CN"
"DateTime::Locale::bo_IN" "DateTime::Locale::bs" "DateTime::Locale::bs_BA"
"DateTime::Locale::byn" "DateTime::Locale::byn_ER" "DateTime::Locale::ca"
"DateTime::Locale::ca_ES" "DateTime::Locale::cch"
"DateTime::Locale::cch_NG" "DateTime::Locale::cop" "DateTime::Locale::cs"
"DateTime::Locale::cs_CZ" "DateTime::Locale::cy" "DateTime::Locale::cy_GB"
"DateTime::Locale::da" "DateTime::Locale::da_DK" "DateTime::Locale::de"
"DateTime::Locale::de_AT" "DateTime::Locale::de_BE"
"DateTime::Locale::de_CH" "DateTime::Locale::de_DE"
"DateTime::Locale::de_LI" "DateTime::Locale::de_LU" "DateTime::Locale::dv"
"DateTime::Locale::dv_MV" "DateTime::Locale::dz" "DateTime::Locale::dz_BT"
"DateTime::Locale::ee" "DateTime::Locale::ee_GH" "DateTime::Locale::ee_TG"
"DateTime::Locale::el" "DateTime::Locale::el_CY" "DateTime::Locale::el_GR"
"DateTime::Locale::el_POLYTON" "DateTime::Locale::en"
"DateTime::Locale::en_AS" "DateTime::Locale::en_AU"
"DateTime::Locale::en_BE" "DateTime::Locale::en_BW"
"DateTime::Locale::en_BZ" "DateTime::Locale::en_CA"
"DateTime::Locale::en_Dsrt" "DateTime::Locale::en_Dsrt_US"
"DateTime::Locale::en_GB" "DateTime::Locale::en_GU"
"DateTime::Locale::en_HK" "DateTime::Locale::en_IE"
"DateTime::Locale::en_IN" "DateTime::Locale::en_JM"
"DateTime::Locale::en_MH" "DateTime::Locale::en_MP"
"DateTime::Locale::en_MT" "DateTime::Locale::en_NA"
"DateTime::Locale::en_NZ" "DateTime::Locale::en_PH"
"DateTime::Locale::en_PK" "DateTime::Locale::en_SG"
"DateTime::Locale::en_Shaw" "DateTime::Locale::en_TT"
"DateTime::Locale::en_UM" "DateTime::Locale::en_US"
"DateTime::Locale::en_US_POSIX" "DateTime::Locale::en_VI"
"DateTime::Locale::en_ZA" "DateTime::Locale::en_ZW" "DateTime::Locale::eo"
"DateTime::Locale::es" "DateTime::Locale::es_AR" "DateTime::Locale::es_BO"
"DateTime::Locale::es_CL" "DateTime::Locale::es_CO"
"DateTime::Locale::es_CR" "DateTime::Locale::es_DO"
"DateTime::Locale::es_EC" "DateTime::Locale::es_ES"
"DateTime::Locale::es_GT" "DateTime::Locale::es_HN"
"DateTime::Locale::es_MX" "DateTime::Locale::es_NI"
"DateTime::Locale::es_PA" "DateTime::Locale::es_PE"
"DateTime::Locale::es_PR" "DateTime::Locale::es_PY"
"DateTime::Locale::es_SV" "DateTime::Locale::es_US"
"DateTime::Locale::es_UY" "DateTime::Locale::es_VE" "DateTime::Locale::et"
"DateTime::Locale::et_EE" "DateTime::Locale::eu" "DateTime::Locale::eu_ES"
"DateTime::Locale::fa" "DateTime::Locale::fa_AF" "DateTime::Locale::fa_IR"
"DateTime::Locale::fi" "DateTime::Locale::fi_FI" "DateTime::Locale::fil"
"DateTime::Locale::fil_PH" "DateTime::Locale::fo" "DateTime::Locale::fo_FO"
"DateTime::Locale::fr" "DateTime::Locale::fr_BE" "DateTime::Locale::fr_CA"
"DateTime::Locale::fr_CH" "DateTime::Locale::fr_FR"
"DateTime::Locale::fr_LU" "DateTime::Locale::fr_MC"
"DateTime::Locale::fr_SN" "DateTime::Locale::fur"
"DateTime::Locale::fur_IT" "DateTime::Locale::ga" "DateTime::Locale::ga_IE"
"DateTime::Locale::gaa" "DateTime::Locale::gaa_GH" "DateTime::Locale::gez"
"DateTime::Locale::gez_ER" "DateTime::Locale::gez_ET"
"DateTime::Locale::gl" "DateTime::Locale::gl_ES" "DateTime::Locale::gsw"
"DateTime::Locale::gsw_CH" "DateTime::Locale::gu" "DateTime::Locale::gu_IN"
"DateTime::Locale::gv" "DateTime::Locale::gv_GB" "DateTime::Locale::ha"
"DateTime::Locale::ha_Arab" "DateTime::Locale::ha_Arab_NG"
"DateTime::Locale::ha_Arab_SD" "DateTime::Locale::ha_GH"
"DateTime::Locale::ha_Latn" "DateTime::Locale::ha_Latn_GH"
"DateTime::Locale::ha_Latn_NE" "DateTime::Locale::ha_Latn_NG"
"DateTime::Locale::ha_NE" "DateTime::Locale::ha_NG"
"DateTime::Locale::ha_SD" "DateTime::Locale::haw"
"DateTime::Locale::haw_US" "DateTime::Locale::he" "DateTime::Locale::he_IL"
"DateTime::Locale::hi" "DateTime::Locale::hi_IN" "DateTime::Locale::hr"
"DateTime::Locale::hr_HR" "DateTime::Locale::hu" "DateTime::Locale::hu_HU"
"DateTime::Locale::hy" "DateTime::Locale::hy_AM"
"DateTime::Locale::hy_AM_REVISED" "DateTime::Locale::ia"
"DateTime::Locale::id" "DateTime::Locale::id_ID" "DateTime::Locale::ig"
"DateTime::Locale::ig_NG" "DateTime::Locale::ii" "DateTime::Locale::ii_CN"
"DateTime::Locale::is" "DateTime::Locale::is_IS" "DateTime::Locale::it"
"DateTime::Locale::it_CH" "DateTime::Locale::it_IT" "DateTime::Locale::iu"
"DateTime::Locale::ja" "DateTime::Locale::ja_JP" "DateTime::Locale::ka"
"DateTime::Locale::ka_GE" "DateTime::Locale::kaj"
"DateTime::Locale::kaj_NG" "DateTime::Locale::kam"
"DateTime::Locale::kam_KE" "DateTime::Locale::kcg"
"DateTime::Locale::kcg_NG" "DateTime::Locale::kfo"
"DateTime::Locale::kfo_CI" "DateTime::Locale::kk"
"DateTime::Locale::kk_Cyrl" "DateTime::Locale::kk_Cyrl_KZ"
"DateTime::Locale::kk_KZ" "DateTime::Locale::kl" "DateTime::Locale::kl_GL"
"DateTime::Locale::km" "DateTime::Locale::km_KH" "DateTime::Locale::kn"
"DateTime::Locale::kn_IN" "DateTime::Locale::ko" "DateTime::Locale::ko_KR"
"DateTime::Locale::kok" "DateTime::Locale::kok_IN" "DateTime::Locale::kpe"
"DateTime::Locale::kpe_GN" "DateTime::Locale::kpe_LR"
"DateTime::Locale::ku" "DateTime::Locale::ku_Arab"
"DateTime::Locale::ku_Arab_IQ" "DateTime::Locale::ku_Arab_IR"
"DateTime::Locale::ku_Arab_SY" "DateTime::Locale::ku_IQ"
"DateTime::Locale::ku_IR" "DateTime::Locale::ku_Latn"
"DateTime::Locale::ku_Latn_TR" "DateTime::Locale::ku_SY"
"DateTime::Locale::ku_TR" "DateTime::Locale::kw" "DateTime::Locale::kw_GB"
"DateTime::Locale::ky" "DateTime::Locale::ky_KG" "DateTime::Locale::ln"
"DateTime::Locale::ln_CD" "DateTime::Locale::ln_CG" "DateTime::Locale::lo"
"DateTime::Locale::lo_LA" "DateTime::Locale::lt" "DateTime::Locale::lt_LT"
"DateTime::Locale::lv" "DateTime::Locale::lv_LV" "DateTime::Locale::mk"
"DateTime::Locale::mk_MK" "DateTime::Locale::ml" "DateTime::Locale::ml_IN"
"DateTime::Locale::mn" "DateTime::Locale::mn_CN"
"DateTime::Locale::mn_Cyrl" "DateTime::Locale::mn_Cyrl_MN"
"DateTime::Locale::mn_MN" "DateTime::Locale::mn_Mong"
"DateTime::Locale::mn_Mong_CN" "DateTime::Locale::mo"
"DateTime::Locale::mr" "DateTime::Locale::mr_IN" "DateTime::Locale::ms"
"DateTime::Locale::ms_BN" "DateTime::Locale::ms_MY" "DateTime::Locale::mt"
"DateTime::Locale::mt_MT" "DateTime::Locale::my" "DateTime::Locale::my_MM"
"DateTime::Locale::nb" "DateTime::Locale::nb_NO" "DateTime::Locale::nds"
"DateTime::Locale::nds_DE" "DateTime::Locale::ne" "DateTime::Locale::ne_IN"
"DateTime::Locale::ne_NP" "DateTime::Locale::nl" "DateTime::Locale::nl_BE"
"DateTime::Locale::nl_NL" "DateTime::Locale::nn" "DateTime::Locale::nn_NO"
"DateTime::Locale::no" "DateTime::Locale::nr" "DateTime::Locale::nr_ZA"
"DateTime::Locale::nso" "DateTime::Locale::nso_ZA" "DateTime::Locale::ny"
"DateTime::Locale::ny_MW" "DateTime::Locale::oc" "DateTime::Locale::oc_FR"
"DateTime::Locale::om" "DateTime::Locale::om_ET" "DateTime::Locale::om_KE"
"DateTime::Locale::or" "DateTime::Locale::or_IN" "DateTime::Locale::pa"
"DateTime::Locale::pa_Arab" "DateTime::Locale::pa_Arab_PK"
"DateTime::Locale::pa_Guru" "DateTime::Locale::pa_Guru_IN"
"DateTime::Locale::pa_IN" "DateTime::Locale::pa_PK" "DateTime::Locale::pl"
"DateTime::Locale::pl_PL" "DateTime::Locale::ps" "DateTime::Locale::ps_AF"
"DateTime::Locale::pt" "DateTime::Locale::pt_BR" "DateTime::Locale::pt_PT"
"DateTime::Locale::ro" "DateTime::Locale::ro_MD" "DateTime::Locale::ro_RO"
"DateTime::Locale::root" "DateTime::Locale::ru" "DateTime::Locale::ru_RU"
"DateTime::Locale::ru_UA" "DateTime::Locale::rw" "DateTime::Locale::rw_RW"
"DateTime::Locale::sa" "DateTime::Locale::sa_IN" "DateTime::Locale::se"
"DateTime::Locale::se_FI" "DateTime::Locale::se_NO" "DateTime::Locale::sh"
"DateTime::Locale::sh_BA" "DateTime::Locale::sh_CS"
"DateTime::Locale::sh_YU" "DateTime::Locale::si" "DateTime::Locale::si_LK"
"DateTime::Locale::sid" "DateTime::Locale::sid_ET" "DateTime::Locale::sk"
"DateTime::Locale::sk_SK" "DateTime::Locale::sl" "DateTime::Locale::sl_SI"
"DateTime::Locale::so" "DateTime::Locale::so_DJ" "DateTime::Locale::so_ET"
"DateTime::Locale::so_KE" "DateTime::Locale::so_SO" "DateTime::Locale::sq"
"DateTime::Locale::sq_AL" "DateTime::Locale::sr" "DateTime::Locale::sr_BA"
"DateTime::Locale::sr_CS" "DateTime::Locale::sr_Cyrl"
"DateTime::Locale::sr_Cyrl_BA" "DateTime::Locale::sr_Cyrl_CS"
"DateTime::Locale::sr_Cyrl_ME" "DateTime::Locale::sr_Cyrl_RS"
"DateTime::Locale::sr_Cyrl_YU" "DateTime::Locale::sr_Latn"
"DateTime::Locale::sr_Latn_BA" "DateTime::Locale::sr_Latn_CS"
"DateTime::Locale::sr_Latn_ME" "DateTime::Locale::sr_Latn_RS"
"DateTime::Locale::sr_Latn_YU" "DateTime::Locale::sr_ME"
"DateTime::Locale::sr_RS" "DateTime::Locale::sr_YU" "DateTime::Locale::ss"
"DateTime::Locale::ss_SZ" "DateTime::Locale::ss_ZA" "DateTime::Locale::st"
"DateTime::Locale::st_LS" "DateTime::Locale::st_ZA" "DateTime::Locale::sv"
"DateTime::Locale::sv_FI" "DateTime::Locale::sv_SE" "DateTime::Locale::sw"
"DateTime::Locale::sw_KE" "DateTime::Locale::sw_TZ" "DateTime::Locale::syr"
"DateTime::Locale::syr_SY" "DateTime::Locale::ta" "DateTime::Locale::ta_IN"
"DateTime::Locale::te" "DateTime::Locale::te_IN" "DateTime::Locale::tg"
"DateTime::Locale::tg_Cyrl" "DateTime::Locale::tg_Cyrl_TJ"
"DateTime::Locale::tg_TJ" "DateTime::Locale::th" "DateTime::Locale::th_TH"
"DateTime::Locale::ti" "DateTime::Locale::ti_ER" "DateTime::Locale::ti_ET"
"DateTime::Locale::tig" "DateTime::Locale::tig_ER" "DateTime::Locale::tl"
"DateTime::Locale::tn" "DateTime::Locale::tn_ZA" "DateTime::Locale::to"
"DateTime::Locale::to_TO" "DateTime::Locale::tr" "DateTime::Locale::tr_TR"
"DateTime::Locale::trv" "DateTime::Locale::trv_TW" "DateTime::Locale::ts"
"DateTime::Locale::ts_ZA" "DateTime::Locale::tt" "DateTime::Locale::tt_RU"
"DateTime::Locale::ug" "DateTime::Locale::ug_Arab"
"DateTime::Locale::ug_Arab_CN" "DateTime::Locale::ug_CN"
"DateTime::Locale::uk" "DateTime::Locale::uk_UA" "DateTime::Locale::ur"
"DateTime::Locale::ur_IN" "DateTime::Locale::ur_PK" "DateTime::Locale::uz"
"DateTime::Locale::uz_AF" "DateTime::Locale::uz_Arab"
"DateTime::Locale::uz_Arab_AF" "DateTime::Locale::uz_Cyrl"
"DateTime::Locale::uz_Cyrl_UZ" "DateTime::Locale::uz_Latn"
"DateTime::Locale::uz_Latn_UZ" "DateTime::Locale::uz_UZ"
"DateTime::Locale::ve" "DateTime::Locale::ve_ZA" "DateTime::Locale::vi"
"DateTime::Locale::vi_VN" "DateTime::Locale::wal"
"DateTime::Locale::wal_ET" "DateTime::Locale::wo"
"DateTime::Locale::wo_Latn" "DateTime::Locale::wo_Latn_SN"
"DateTime::Locale::wo_SN" "DateTime::Locale::xh" "DateTime::Locale::xh_ZA"
"DateTime::Locale::yo" "DateTime::Locale::yo_NG" "DateTime::Locale::zh"
"DateTime::Locale::zh_CN" "DateTime::Locale::zh_HK"
"DateTime::Locale::zh_Hans" "DateTime::Locale::zh_Hans_CN"
"DateTime::Locale::zh_Hans_HK" "DateTime::Locale::zh_Hans_MO"
"DateTime::Locale::zh_Hans_SG" "DateTime::Locale::zh_Hant"
"DateTime::Locale::zh_Hant_HK" "DateTime::Locale::zh_Hant_MO"
"DateTime::Locale::zh_Hant_TW" "DateTime::Locale::zh_MO"
"DateTime::Locale::zh_SG" "DateTime::Locale::zh_TW" "DateTime::Locale::zu"
"DateTime::Locale::zu_ZA" "DateTime::LocaleCatalog" "DateTime::TimeZone"
"DateTime::TimeZone::Africa::Abidjan" "DateTime::TimeZone::Africa::Accra"
"DateTime::TimeZone::Africa::Addis_Ababa"
"DateTime::TimeZone::Africa::Algiers" "DateTime::TimeZone::Africa::Asmara"
"DateTime::TimeZone::Africa::Bamako" "DateTime::TimeZone::Africa::Bangui"
"DateTime::TimeZone::Africa::Banjul" "DateTime::TimeZone::Africa::Bissau"
"DateTime::TimeZone::Africa::Blantyre"
"DateTime::TimeZone::Africa::Brazzaville"
"DateTime::TimeZone::Africa::Bujumbura" "DateTime::TimeZone::Africa::Cairo"
"DateTime::TimeZone::Africa::Casablanca"
"DateTime::TimeZone::Africa::Ceuta" "DateTime::TimeZone::Africa::Conakry"
"DateTime::TimeZone::Africa::Dakar"
"DateTime::TimeZone::Africa::Dar_es_Salaam"
"DateTime::TimeZone::Africa::Djibouti" "DateTime::TimeZone::Africa::Douala"
"DateTime::TimeZone::Africa::El_Aaiun"
"DateTime::TimeZone::Africa::Freetown"
"DateTime::TimeZone::Africa::Gaborone" "DateTime::TimeZone::Africa::Harare"
"DateTime::TimeZone::Africa::Johannesburg"
"DateTime::TimeZone::Africa::Kampala"
"DateTime::TimeZone::Africa::Khartoum" "DateTime::TimeZone::Africa::Kigali"
"DateTime::TimeZone::Africa::Kinshasa" "DateTime::TimeZone::Africa::Lagos"
"DateTime::TimeZone::Africa::Libreville" "DateTime::TimeZone::Africa::Lome"
"DateTime::TimeZone::Africa::Luanda"
"DateTime::TimeZone::Africa::Lubumbashi"
"DateTime::TimeZone::Africa::Lusaka" "DateTime::TimeZone::Africa::Malabo"
"DateTime::TimeZone::Africa::Maputo" "DateTime::TimeZone::Africa::Maseru"
"DateTime::TimeZone::Africa::Mbabane"
"DateTime::TimeZone::Africa::Mogadishu"
"DateTime::TimeZone::Africa::Monrovia"
"DateTime::TimeZone::Africa::Nairobi"
"DateTime::TimeZone::Africa::Ndjamena" "DateTime::TimeZone::Africa::Niamey"
"DateTime::TimeZone::Africa::Nouakchott"
"DateTime::TimeZone::Africa::Ouagadougou"
"DateTime::TimeZone::Africa::Porto_Novo"
"DateTime::TimeZone::Africa::Sao_Tome"
"DateTime::TimeZone::Africa::Tripoli" "DateTime::TimeZone::Africa::Tunis"
"DateTime::TimeZone::Africa::Windhoek" "DateTime::TimeZone::America::Adak"
"DateTime::TimeZone::America::Anchorage"
"DateTime::TimeZone::America::Anguilla"
"DateTime::TimeZone::America::Antigua"
"DateTime::TimeZone::America::Araguaina"
"DateTime::TimeZone::America::Argentina::Buenos_Aires"
"DateTime::TimeZone::America::Argentina::Catamarca"
"DateTime::TimeZone::America::Argentina::Cordoba"
"DateTime::TimeZone::America::Argentina::Jujuy"
"DateTime::TimeZone::America::Argentina::La_Rioja"
"DateTime::TimeZone::America::Argentina::Mendoza"
"DateTime::TimeZone::America::Argentina::Rio_Gallegos"
"DateTime::TimeZone::America::Argentina::Salta"
"DateTime::TimeZone::America::Argentina::San_Juan"
"DateTime::TimeZone::America::Argentina::San_Luis"
"DateTime::TimeZone::America::Argentina::Tucuman"
"DateTime::TimeZone::America::Argentina::Ushuaia"
"DateTime::TimeZone::America::Aruba"
"DateTime::TimeZone::America::Asuncion"
"DateTime::TimeZone::America::Atikokan"
"DateTime::TimeZone::America::Bahia"
"DateTime::TimeZone::America::Barbados"
"DateTime::TimeZone::America::Belem" "DateTime::TimeZone::America::Belize"
"DateTime::TimeZone::America::Blanc_Sablon"
"DateTime::TimeZone::America::Boa_Vista"
"DateTime::TimeZone::America::Bogota" "DateTime::TimeZone::America::Boise"
"DateTime::TimeZone::America::Cambridge_Bay"
"DateTime::TimeZone::America::Campo_Grande"
"DateTime::TimeZone::America::Cancun"
"DateTime::TimeZone::America::Caracas"
"DateTime::TimeZone::America::Cayenne"
"DateTime::TimeZone::America::Cayman"
"DateTime::TimeZone::America::Chicago"
"DateTime::TimeZone::America::Chihuahua"
"DateTime::TimeZone::America::Costa_Rica"
"DateTime::TimeZone::America::Cuiaba"
"DateTime::TimeZone::America::Curacao"
"DateTime::TimeZone::America::Danmarkshavn"
"DateTime::TimeZone::America::Dawson"
"DateTime::TimeZone::America::Dawson_Creek"
"DateTime::TimeZone::America::Denver"
"DateTime::TimeZone::America::Detroit"
"DateTime::TimeZone::America::Dominica"
"DateTime::TimeZone::America::Edmonton"
"DateTime::TimeZone::America::Eirunepe"
"DateTime::TimeZone::America::El_Salvador"
"DateTime::TimeZone::America::Fortaleza"
"DateTime::TimeZone::America::Glace_Bay"
"DateTime::TimeZone::America::Godthab"
"DateTime::TimeZone::America::Goose_Bay"
"DateTime::TimeZone::America::Grand_Turk"
"DateTime::TimeZone::America::Grenada"
"DateTime::TimeZone::America::Guadeloupe"
"DateTime::TimeZone::America::Guatemala"
"DateTime::TimeZone::America::Guayaquil"
"DateTime::TimeZone::America::Guyana"
"DateTime::TimeZone::America::Halifax"
"DateTime::TimeZone::America::Havana"
"DateTime::TimeZone::America::Hermosillo"
"DateTime::TimeZone::America::Indiana::Indianapolis"
"DateTime::TimeZone::America::Indiana::Knox"
"DateTime::TimeZone::America::Indiana::Marengo"
"DateTime::TimeZone::America::Indiana::Petersburg"
"DateTime::TimeZone::America::Indiana::Tell_City"
"DateTime::TimeZone::America::Indiana::Vevay"
"DateTime::TimeZone::America::Indiana::Vincennes"
"DateTime::TimeZone::America::Indiana::Winamac"
"DateTime::TimeZone::America::Inuvik"
"DateTime::TimeZone::America::Iqaluit"
"DateTime::TimeZone::America::Jamaica"
"DateTime::TimeZone::America::Juneau"
"DateTime::TimeZone::America::Kentucky::Louisville"
"DateTime::TimeZone::America::Kentucky::Monticello"
"DateTime::TimeZone::America::La_Paz" "DateTime::TimeZone::America::Lima"
"DateTime::TimeZone::America::Los_Angeles"
"DateTime::TimeZone::America::Maceio"
"DateTime::TimeZone::America::Managua"
"DateTime::TimeZone::America::Manaus"
"DateTime::TimeZone::America::Martinique"
"DateTime::TimeZone::America::Matamoros"
"DateTime::TimeZone::America::Mazatlan"
"DateTime::TimeZone::America::Menominee"
"DateTime::TimeZone::America::Merida"
"DateTime::TimeZone::America::Mexico_City"
"DateTime::TimeZone::America::Miquelon"
"DateTime::TimeZone::America::Moncton"
"DateTime::TimeZone::America::Monterrey"
"DateTime::TimeZone::America::Montevideo"
"DateTime::TimeZone::America::Montreal"
"DateTime::TimeZone::America::Montserrat"
"DateTime::TimeZone::America::Nassau"
"DateTime::TimeZone::America::New_York"
"DateTime::TimeZone::America::Nipigon" "DateTime::TimeZone::America::Nome"
"DateTime::TimeZone::America::Noronha"
"DateTime::TimeZone::America::North_Dakota::Center"
"DateTime::TimeZone::America::North_Dakota::New_Salem"
"DateTime::TimeZone::America::Ojinaga"
"DateTime::TimeZone::America::Panama"
"DateTime::TimeZone::America::Pangnirtung"
"DateTime::TimeZone::America::Paramaribo"
"DateTime::TimeZone::America::Phoenix"
"DateTime::TimeZone::America::Port_au_Prince"
"DateTime::TimeZone::America::Port_of_Spain"
"DateTime::TimeZone::America::Porto_Velho"
"DateTime::TimeZone::America::Puerto_Rico"
"DateTime::TimeZone::America::Rainy_River"
"DateTime::TimeZone::America::Rankin_Inlet"
"DateTime::TimeZone::America::Recife" "DateTime::TimeZone::America::Regina"
"DateTime::TimeZone::America::Resolute"
"DateTime::TimeZone::America::Rio_Branco"
"DateTime::TimeZone::America::Santa_Isabel"
"DateTime::TimeZone::America::Santarem"
"DateTime::TimeZone::America::Santiago"
"DateTime::TimeZone::America::Santo_Domingo"
"DateTime::TimeZone::America::Sao_Paulo"
"DateTime::TimeZone::America::Scoresbysund"
"DateTime::TimeZone::America::St_Johns"
"DateTime::TimeZone::America::St_Kitts"
"DateTime::TimeZone::America::St_Lucia"
"DateTime::TimeZone::America::St_Thomas"
"DateTime::TimeZone::America::St_Vincent"
"DateTime::TimeZone::America::Swift_Current"
"DateTime::TimeZone::America::Tegucigalpa"
"DateTime::TimeZone::America::Thule"
"DateTime::TimeZone::America::Thunder_Bay"
"DateTime::TimeZone::America::Tijuana"
"DateTime::TimeZone::America::Toronto"
"DateTime::TimeZone::America::Tortola"
"DateTime::TimeZone::America::Vancouver"
"DateTime::TimeZone::America::Whitehorse"
"DateTime::TimeZone::America::Winnipeg"
"DateTime::TimeZone::America::Yakutat"
"DateTime::TimeZone::America::Yellowknife"
"DateTime::TimeZone::Antarctica::Casey"
"DateTime::TimeZone::Antarctica::Davis"
"DateTime::TimeZone::Antarctica::DumontDUrville"
"DateTime::TimeZone::Antarctica::Mawson"
"DateTime::TimeZone::Antarctica::McMurdo"
"DateTime::TimeZone::Antarctica::Palmer"
"DateTime::TimeZone::Antarctica::Rothera"
"DateTime::TimeZone::Antarctica::Syowa"
"DateTime::TimeZone::Antarctica::Vostok" "DateTime::TimeZone::Asia::Aden"
"DateTime::TimeZone::Asia::Almaty" "DateTime::TimeZone::Asia::Amman"
"DateTime::TimeZone::Asia::Anadyr" "DateTime::TimeZone::Asia::Aqtau"
"DateTime::TimeZone::Asia::Aqtobe" "DateTime::TimeZone::Asia::Ashgabat"
"DateTime::TimeZone::Asia::Baghdad" "DateTime::TimeZone::Asia::Bahrain"
"DateTime::TimeZone::Asia::Baku" "DateTime::TimeZone::Asia::Bangkok"
"DateTime::TimeZone::Asia::Beirut" "DateTime::TimeZone::Asia::Bishkek"
"DateTime::TimeZone::Asia::Brunei" "DateTime::TimeZone::Asia::Choibalsan"
"DateTime::TimeZone::Asia::Chongqing" "DateTime::TimeZone::Asia::Colombo"
"DateTime::TimeZone::Asia::Damascus" "DateTime::TimeZone::Asia::Dhaka"
"DateTime::TimeZone::Asia::Dili" "DateTime::TimeZone::Asia::Dubai"
"DateTime::TimeZone::Asia::Dushanbe" "DateTime::TimeZone::Asia::Gaza"
"DateTime::TimeZone::Asia::Harbin" "DateTime::TimeZone::Asia::Ho_Chi_Minh"
"DateTime::TimeZone::Asia::Hong_Kong" "DateTime::TimeZone::Asia::Hovd"
"DateTime::TimeZone::Asia::Irkutsk" "DateTime::TimeZone::Asia::Jakarta"
"DateTime::TimeZone::Asia::Jayapura" "DateTime::TimeZone::Asia::Jerusalem"
"DateTime::TimeZone::Asia::Kabul" "DateTime::TimeZone::Asia::Kamchatka"
"DateTime::TimeZone::Asia::Karachi" "DateTime::TimeZone::Asia::Kashgar"
"DateTime::TimeZone::Asia::Kathmandu" "DateTime::TimeZone::Asia::Kolkata"
"DateTime::TimeZone::Asia::Krasnoyarsk"
"DateTime::TimeZone::Asia::Kuala_Lumpur"
"DateTime::TimeZone::Asia::Kuching" "DateTime::TimeZone::Asia::Kuwait"
"DateTime::TimeZone::Asia::Macau" "DateTime::TimeZone::Asia::Magadan"
"DateTime::TimeZone::Asia::Makassar" "DateTime::TimeZone::Asia::Manila"
"DateTime::TimeZone::Asia::Muscat" "DateTime::TimeZone::Asia::Nicosia"
"DateTime::TimeZone::Asia::Novokuznetsk"
"DateTime::TimeZone::Asia::Novosibirsk" "DateTime::TimeZone::Asia::Omsk"
"DateTime::TimeZone::Asia::Oral" "DateTime::TimeZone::Asia::Phnom_Penh"
"DateTime::TimeZone::Asia::Pontianak" "DateTime::TimeZone::Asia::Pyongyang"
"DateTime::TimeZone::Asia::Qatar" "DateTime::TimeZone::Asia::Qyzylorda"
"DateTime::TimeZone::Asia::Rangoon" "DateTime::TimeZone::Asia::Riyadh"
"DateTime::TimeZone::Asia::Sakhalin" "DateTime::TimeZone::Asia::Samarkand"
"DateTime::TimeZone::Asia::Seoul" "DateTime::TimeZone::Asia::Shanghai"
"DateTime::TimeZone::Asia::Singapore" "DateTime::TimeZone::Asia::Taipei"
"DateTime::TimeZone::Asia::Tashkent" "DateTime::TimeZone::Asia::Tbilisi"
"DateTime::TimeZone::Asia::Tehran" "DateTime::TimeZone::Asia::Thimphu"
"DateTime::TimeZone::Asia::Tokyo" "DateTime::TimeZone::Asia::Ulaanbaatar"
"DateTime::TimeZone::Asia::Urumqi" "DateTime::TimeZone::Asia::Vientiane"
"DateTime::TimeZone::Asia::Vladivostok" "DateTime::TimeZone::Asia::Yakutsk"
"DateTime::TimeZone::Asia::Yekaterinburg"
"DateTime::TimeZone::Asia::Yerevan" "DateTime::TimeZone::Atlantic::Azores"
"DateTime::TimeZone::Atlantic::Bermuda"
"DateTime::TimeZone::Atlantic::Canary"
"DateTime::TimeZone::Atlantic::Cape_Verde"
"DateTime::TimeZone::Atlantic::Faroe"
"DateTime::TimeZone::Atlantic::Madeira"
"DateTime::TimeZone::Atlantic::Reykjavik"
"DateTime::TimeZone::Atlantic::South_Georgia"
"DateTime::TimeZone::Atlantic::St_Helena"
"DateTime::TimeZone::Atlantic::Stanley"
"DateTime::TimeZone::Australia::Adelaide"
"DateTime::TimeZone::Australia::Brisbane"
"DateTime::TimeZone::Australia::Broken_Hill"
"DateTime::TimeZone::Australia::Currie"
"DateTime::TimeZone::Australia::Darwin"
"DateTime::TimeZone::Australia::Eucla"
"DateTime::TimeZone::Australia::Hobart"
"DateTime::TimeZone::Australia::Lindeman"
"DateTime::TimeZone::Australia::Lord_Howe"
"DateTime::TimeZone::Australia::Melbourne"
"DateTime::TimeZone::Australia::Perth"
"DateTime::TimeZone::Australia::Sydney" "DateTime::TimeZone::CET"
"DateTime::TimeZone::CST6CDT" "DateTime::TimeZone::Catalog"
"DateTime::TimeZone::EET" "DateTime::TimeZone::EST"
"DateTime::TimeZone::EST5EDT" "DateTime::TimeZone::Europe::Amsterdam"
"DateTime::TimeZone::Europe::Andorra" "DateTime::TimeZone::Europe::Athens"
"DateTime::TimeZone::Europe::Belgrade" "DateTime::TimeZone::Europe::Berlin"
"DateTime::TimeZone::Europe::Brussels"
"DateTime::TimeZone::Europe::Bucharest"
"DateTime::TimeZone::Europe::Budapest"
"DateTime::TimeZone::Europe::Chisinau"
"DateTime::TimeZone::Europe::Copenhagen"
"DateTime::TimeZone::Europe::Dublin"
"DateTime::TimeZone::Europe::Gibraltar"
"DateTime::TimeZone::Europe::Helsinki"
"DateTime::TimeZone::Europe::Istanbul"
"DateTime::TimeZone::Europe::Kaliningrad"
"DateTime::TimeZone::Europe::Kiev" "DateTime::TimeZone::Europe::Lisbon"
"DateTime::TimeZone::Europe::London"
"DateTime::TimeZone::Europe::Luxembourg"
"DateTime::TimeZone::Europe::Madrid" "DateTime::TimeZone::Europe::Malta"
"DateTime::TimeZone::Europe::Minsk" "DateTime::TimeZone::Europe::Monaco"
"DateTime::TimeZone::Europe::Moscow" "DateTime::TimeZone::Europe::Oslo"
"DateTime::TimeZone::Europe::Paris" "DateTime::TimeZone::Europe::Prague"
"DateTime::TimeZone::Europe::Riga" "DateTime::TimeZone::Europe::Rome"
"DateTime::TimeZone::Europe::Samara"
"DateTime::TimeZone::Europe::Simferopol"
"DateTime::TimeZone::Europe::Sofia" "DateTime::TimeZone::Europe::Stockholm"
"DateTime::TimeZone::Europe::Tallinn" "DateTime::TimeZone::Europe::Tirane"
"DateTime::TimeZone::Europe::Uzhgorod" "DateTime::TimeZone::Europe::Vaduz"
"DateTime::TimeZone::Europe::Vienna" "DateTime::TimeZone::Europe::Vilnius"
"DateTime::TimeZone::Europe::Volgograd"
"DateTime::TimeZone::Europe::Warsaw"
"DateTime::TimeZone::Europe::Zaporozhye"
"DateTime::TimeZone::Europe::Zurich" "DateTime::TimeZone::Floating"
"DateTime::TimeZone::HST" "DateTime::TimeZone::Indian::Antananarivo"
"DateTime::TimeZone::Indian::Chagos"
"DateTime::TimeZone::Indian::Christmas" "DateTime::TimeZone::Indian::Cocos"
"DateTime::TimeZone::Indian::Comoro"
"DateTime::TimeZone::Indian::Kerguelen" "DateTime::TimeZone::Indian::Mahe"
"DateTime::TimeZone::Indian::Maldives"
"DateTime::TimeZone::Indian::Mauritius"
"DateTime::TimeZone::Indian::Mayotte" "DateTime::TimeZone::Indian::Reunion"
"DateTime::TimeZone::Local" "DateTime::TimeZone::Local::Unix"
"DateTime::TimeZone::Local::VMS" "DateTime::TimeZone::Local::Win32"
"DateTime::TimeZone::MET" "DateTime::TimeZone::MST"
"DateTime::TimeZone::MST7MDT" "DateTime::TimeZone::OffsetOnly"
"DateTime::TimeZone::OlsonDB" "DateTime::TimeZone::OlsonDB::Change"
"DateTime::TimeZone::OlsonDB::Observance"
"DateTime::TimeZone::OlsonDB::Rule" "DateTime::TimeZone::OlsonDB::Zone"
"DateTime::TimeZone::PST8PDT" "DateTime::TimeZone::Pacific::Apia"
"DateTime::TimeZone::Pacific::Auckland"
"DateTime::TimeZone::Pacific::Chatham"
"DateTime::TimeZone::Pacific::Easter" "DateTime::TimeZone::Pacific::Efate"
"DateTime::TimeZone::Pacific::Enderbury"
"DateTime::TimeZone::Pacific::Fakaofo" "DateTime::TimeZone::Pacific::Fiji"
"DateTime::TimeZone::Pacific::Funafuti"
"DateTime::TimeZone::Pacific::Galapagos"
"DateTime::TimeZone::Pacific::Gambier"
"DateTime::TimeZone::Pacific::Guadalcanal"
"DateTime::TimeZone::Pacific::Guam" "DateTime::TimeZone::Pacific::Honolulu"
"DateTime::TimeZone::Pacific::Johnston"
"DateTime::TimeZone::Pacific::Kiritimati"
"DateTime::TimeZone::Pacific::Kosrae"
"DateTime::TimeZone::Pacific::Kwajalein"
"DateTime::TimeZone::Pacific::Majuro"
"DateTime::TimeZone::Pacific::Marquesas"
"DateTime::TimeZone::Pacific::Midway" "DateTime::TimeZone::Pacific::Nauru"
"DateTime::TimeZone::Pacific::Niue" "DateTime::TimeZone::Pacific::Norfolk"
"DateTime::TimeZone::Pacific::Noumea"
"DateTime::TimeZone::Pacific::Pago_Pago"
"DateTime::TimeZone::Pacific::Palau"
"DateTime::TimeZone::Pacific::Pitcairn"
"DateTime::TimeZone::Pacific::Ponape"
"DateTime::TimeZone::Pacific::Port_Moresby"
"DateTime::TimeZone::Pacific::Rarotonga"
"DateTime::TimeZone::Pacific::Saipan" "DateTime::TimeZone::Pacific::Tahiti"
"DateTime::TimeZone::Pacific::Tarawa"
"DateTime::TimeZone::Pacific::Tongatapu"
"DateTime::TimeZone::Pacific::Truk" "DateTime::TimeZone::Pacific::Wake"
"DateTime::TimeZone::Pacific::Wallis" "DateTime::TimeZone::UTC"
"DateTime::TimeZone::WET" "DateTimePP" "DateTimePPExtra" "Devel::DProf"
"Devel::InnerPackage" "Devel::PPPort" "Devel::Peek" "Devel::SelfStubber"
"Digest" "Digest::HMAC" "Digest::HMAC_MD5" "Digest::HMAC_SHA1"
"Digest::MD5" "Digest::SHA" "Digest::SHA1" "Digest::base" "Digest::file"
"DirHandle" "Dumpvalue" "DynaLoader" "Email::Date::Format" "Encode"
"Encode::Alias" "Encode::Byte" "Encode::CJKConstants" "Encode::CN"
"Encode::CN::HZ" "Encode::Config" "Encode::Detect"
"Encode::Detect::Detector" "Encode::EBCDIC" "Encode::Encoder"
"Encode::Encoding" "Encode::GSM0338" "Encode::Guess" "Encode::JP"
"Encode::JP::H2Z" "Encode::JP::JIS7" "Encode::KR" "Encode::KR::2022_KR"
"Encode::MIME::Header" "Encode::MIME::Header::ISO_2022_JP"
"Encode::MIME::Name" "Encode::PerlIO" "Encode::Supported" "Encode::Symbol"
"Encode::TW" "Encode::Unicode" "Encode::Unicode::UTF7" "English" "Env"
"Errno" "Error" "Error::Simple" "Exporter" "Exporter::Heavy"
"ExtUtils::Command" "ExtUtils::Command::MM" "ExtUtils::Constant"
"ExtUtils::Constant::Base" "ExtUtils::Constant::ProxySubs"
"ExtUtils::Constant::Utils" "ExtUtils::Constant::XS" "ExtUtils::Install"
"ExtUtils::Installed" "ExtUtils::Liblist" "ExtUtils::Liblist::Kid"
"ExtUtils::MM" "ExtUtils::MM_AIX" "ExtUtils::MM_Any" "ExtUtils::MM_BeOS"
"ExtUtils::MM_Cygwin" "ExtUtils::MM_DOS" "ExtUtils::MM_Darwin"
"ExtUtils::MM_MacOS" "ExtUtils::MM_NW5" "ExtUtils::MM_OS2"
"ExtUtils::MM_QNX" "ExtUtils::MM_UWIN" "ExtUtils::MM_Unix"
"ExtUtils::MM_VMS" "ExtUtils::MM_VOS" "ExtUtils::MM_Win32"
"ExtUtils::MM_Win95" "ExtUtils::MY" "ExtUtils::MakeMaker"
"ExtUtils::MakeMaker::Config" "ExtUtils::MakeMaker::FAQ"
"ExtUtils::MakeMaker::Tutorial" "ExtUtils::Manifest" "ExtUtils::Miniperl"
"ExtUtils::Mkbootstrap" "ExtUtils::Mksymlists" "ExtUtils::Packlist"
"ExtUtils::ParseXS" "ExtUtils::testlib" "FCGI" "Fatal" "Fcntl"
"File::Basename" "File::CheckTree" "File::Compare" "File::Copy"
"File::DosGlob" "File::Find" "File::Glob" "File::GlobMapper"
"File::Listing" "File::Path" "File::RandomAccess" "File::RsyncP"
"File::RsyncP::Digest" "File::RsyncP::FileIO" "File::RsyncP::FileList"
"File::Spec" "File::Spec::Cygwin" "File::Spec::Epoc"
"File::Spec::Functions" "File::Spec::Mac" "File::Spec::OS2"
"File::Spec::Unix" "File::Spec::VMS" "File::Spec::Win32" "File::Temp"
"File::stat" "FileCache" "FileHandle" "Filter::Simple" "Filter::Util::Call"
"FindBin" "Foomatic::DB" "Foomatic::Defaults" "Foomatic::PPD"
"Foomatic::UIElem" "GDBM_File" "Getopt::Long" "Getopt::Std" "Git"
"HTML::Entities" "HTML::Filter" "HTML::Form" "HTML::HeadParser"
"HTML::LinkExtor" "HTML::Parser" "HTML::PullParser" "HTML::Tagset"
"HTML::TokeParser" "HTTP::Config" "HTTP::Cookies"
"HTTP::Cookies::Microsoft" "HTTP::Cookies::Netscape" "HTTP::Daemon"
"HTTP::Date" "HTTP::Headers" "HTTP::Headers::Auth" "HTTP::Headers::ETag"
"HTTP::Headers::Util" "HTTP::Message" "HTTP::Negotiate" "HTTP::Request"
"HTTP::Request::Common" "HTTP::Response" "HTTP::Status" "Hash::Util"
"Hash::Util::FieldHash" "I18N::Collate" "I18N::LangTags"
"I18N::LangTags::Detect" "I18N::LangTags::List" "I18N::Langinfo" "IO"
"IO::Compress::Adapter::Bzip2" "IO::Compress::Adapter::Deflate"
"IO::Compress::Adapter::Identity" "IO::Compress::Base"
"IO::Compress::Base::Common" "IO::Compress::Bzip2" "IO::Compress::Deflate"
"IO::Compress::Gzip" "IO::Compress::Gzip::Constants"
"IO::Compress::RawDeflate" "IO::Compress::Zip"
"IO::Compress::Zip::Constants" "IO::Compress::Zlib::Constants"
"IO::Compress::Zlib::Extra" "IO::Dir" "IO::File" "IO::Handle" "IO::Pipe"
"IO::Poll" "IO::Seekable" "IO::Select" "IO::Socket" "IO::Socket::INET"
"IO::Socket::INET6" "IO::Socket::SSL" "IO::Socket::UNIX"
"IO::Uncompress::Adapter::Bunzip2" "IO::Uncompress::Adapter::Identity"
"IO::Uncompress::Adapter::Inflate" "IO::Uncompress::AnyInflate"
"IO::Uncompress::AnyUncompress" "IO::Uncompress::Base"
"IO::Uncompress::Bunzip2" "IO::Uncompress::Gunzip"
"IO::Uncompress::Inflate" "IO::Uncompress::RawInflate"
"IO::Uncompress::Unzip" "IO::Zlib" "IPC::Msg" "IPC::Open2" "IPC::Open3"
"IPC::Semaphore" "IPC::SharedMem" "IPC::SysV" "Image::ExifTool"
"Image::ExifTool::AES" "Image::ExifTool::AFCP" "Image::ExifTool::AIFF"
"Image::ExifTool::APE" "Image::ExifTool::APP12" "Image::ExifTool::ASF"
"Image::ExifTool::BMP" "Image::ExifTool::BZZ" "Image::ExifTool::BigTIFF"
"Image::ExifTool::BuildTagLookup" "Image::ExifTool::Canon"
"Image::ExifTool::CanonCustom" "Image::ExifTool::CanonRaw"
"Image::ExifTool::CanonVRD" "Image::ExifTool::CaptureOne"
"Image::ExifTool::Casio" "Image::ExifTool::Charset"
"Image::ExifTool::Charset::Arabic" "Image::ExifTool::Charset::Baltic"
"Image::ExifTool::Charset::Cyrillic" "Image::ExifTool::Charset::Greek"
"Image::ExifTool::Charset::Hebrew" "Image::ExifTool::Charset::JIS"
"Image::ExifTool::Charset::Latin" "Image::ExifTool::Charset::Latin2"
"Image::ExifTool::Charset::MacArabic"
"Image::ExifTool::Charset::MacChineseCN"
"Image::ExifTool::Charset::MacChineseTW"
"Image::ExifTool::Charset::MacCroatian"
"Image::ExifTool::Charset::MacCyrillic"
"Image::ExifTool::Charset::MacGreek" "Image::ExifTool::Charset::MacHebrew"
"Image::ExifTool::Charset::MacIceland"
"Image::ExifTool::Charset::MacJapanese"
"Image::ExifTool::Charset::MacKorean" "Image::ExifTool::Charset::MacLatin2"
"Image::ExifTool::Charset::MacRSymbol" "Image::ExifTool::Charset::MacRoman"
"Image::ExifTool::Charset::MacRomanian" "Image::ExifTool::Charset::MacThai"
"Image::ExifTool::Charset::MacTurkish" "Image::ExifTool::Charset::PDFDoc"
"Image::ExifTool::Charset::ShiftJIS" "Image::ExifTool::Charset::Symbol"
"Image::ExifTool::Charset::Thai" "Image::ExifTool::Charset::Turkish"
"Image::ExifTool::Charset::Vietnam" "Image::ExifTool::DICOM"
"Image::ExifTool::DNG" "Image::ExifTool::DjVu" "Image::ExifTool::EXE"
"Image::ExifTool::Exif" "Image::ExifTool::FLAC" "Image::ExifTool::Fixup"
"Image::ExifTool::Flash" "Image::ExifTool::FlashPix"
"Image::ExifTool::Font" "Image::ExifTool::FotoStation"
"Image::ExifTool::FujiFilm" "Image::ExifTool::GIF" "Image::ExifTool::GIMP"
"Image::ExifTool::GPS" "Image::ExifTool::GeoTiff" "Image::ExifTool::Geotag"
"Image::ExifTool::H264" "Image::ExifTool::HP" "Image::ExifTool::HTML"
"Image::ExifTool::HtmlDump" "Image::ExifTool::ICC_Profile"
"Image::ExifTool::ID3" "Image::ExifTool::IPTC" "Image::ExifTool::ITC"
"Image::ExifTool::InDesign" "Image::ExifTool::JPEG"
"Image::ExifTool::JPEGDigest" "Image::ExifTool::JVC"
"Image::ExifTool::Jpeg2000" "Image::ExifTool::Kodak"
"Image::ExifTool::KyoceraRaw" "Image::ExifTool::LNK"
"Image::ExifTool::Lang::cs" "Image::ExifTool::Lang::de"
"Image::ExifTool::Lang::en_ca" "Image::ExifTool::Lang::en_gb"
"Image::ExifTool::Lang::es" "Image::ExifTool::Lang::fr"
"Image::ExifTool::Lang::it" "Image::ExifTool::Lang::ja"
"Image::ExifTool::Lang::ko" "Image::ExifTool::Lang::nl"
"Image::ExifTool::Lang::pl" "Image::ExifTool::Lang::ru"
"Image::ExifTool::Lang::sv" "Image::ExifTool::Lang::tr"
"Image::ExifTool::Lang::zh_cn" "Image::ExifTool::Lang::zh_tw"
"Image::ExifTool::Leaf" "Image::ExifTool::M2TS" "Image::ExifTool::MIE"
"Image::ExifTool::MIEUnits" "Image::ExifTool::MIFF" "Image::ExifTool::MNG"
"Image::ExifTool::MPC" "Image::ExifTool::MPEG" "Image::ExifTool::MPF"
"Image::ExifTool::MWG" "Image::ExifTool::MakerNotes"
"Image::ExifTool::Matroska" "Image::ExifTool::Microsoft"
"Image::ExifTool::Minolta" "Image::ExifTool::MinoltaRaw"
"Image::ExifTool::Nikon" "Image::ExifTool::NikonCapture"
"Image::ExifTool::NikonCustom" "Image::ExifTool::OOXML"
"Image::ExifTool::Olympus" "Image::ExifTool::PDF" "Image::ExifTool::PICT"
"Image::ExifTool::PNG" "Image::ExifTool::PPM" "Image::ExifTool::PSP"
"Image::ExifTool::Panasonic" "Image::ExifTool::PanasonicRaw"
"Image::ExifTool::Pentax" "Image::ExifTool::PhotoMechanic"
"Image::ExifTool::Photoshop" "Image::ExifTool::PostScript"
"Image::ExifTool::PrintIM" "Image::ExifTool::QuickTime"
"Image::ExifTool::RIFF" "Image::ExifTool::RSRC" "Image::ExifTool::RTF"
"Image::ExifTool::Rawzor" "Image::ExifTool::Real" "Image::ExifTool::Ricoh"
"Image::ExifTool::Samsung" "Image::ExifTool::Sanyo"
"Image::ExifTool::Shortcuts" "Image::ExifTool::Sigma"
"Image::ExifTool::SigmaRaw" "Image::ExifTool::Sony"
"Image::ExifTool::SonyIDC" "Image::ExifTool::Stim"
"Image::ExifTool::TagInfoXML" "Image::ExifTool::TagLookup"
"Image::ExifTool::TagNames" "Image::ExifTool::Unknown"
"Image::ExifTool::Vorbis" "Image::ExifTool::XMP" "Image::ExifTool::XMP2"
"Image::ExifTool::ZIP" "Image::ExifTool::iWork" "LWP" "LWP::Authen::Basic"
"LWP::Authen::Digest" "LWP::Authen::Ntlm" "LWP::ConnCache" "LWP::Debug"
"LWP::DebugFile" "LWP::MediaTypes" "LWP::MemberMixin" "LWP::Protocol"
"LWP::Protocol::GHTTP" "LWP::Protocol::cpan" "LWP::Protocol::data"
"LWP::Protocol::file" "LWP::Protocol::ftp" "LWP::Protocol::gopher"
"LWP::Protocol::http" "LWP::Protocol::http10" "LWP::Protocol::https"
"LWP::Protocol::https10" "LWP::Protocol::loopback" "LWP::Protocol::mailto"
"LWP::Protocol::nntp" "LWP::Protocol::nogo" "LWP::RobotUA" "LWP::Simple"
"LWP::UserAgent" "List::MoreUtils" "List::Util" "List::Util::PP"
"List::Util::XS" "Locale::Constants" "Locale::Country" "Locale::Currency"
"Locale::Language" "Locale::Maketext" "Locale::Maketext::Guts"
"Locale::Maketext::GutsLoader" "Locale::Maketext::TPJ13" "Locale::Script"
"MIME::Base64" "MIME::Lite" "MIME::QuotedPrint" "MIME::Type" "MIME::Types"
"Mail::Address" "Mail::Cap" "Mail::DKIM" "Mail::DKIM::Algorithm::Base"
"Mail::DKIM::Algorithm::dk_rsa_sha1" "Mail::DKIM::Algorithm::rsa_sha1"
"Mail::DKIM::Algorithm::rsa_sha256" "Mail::DKIM::AuthorDomainPolicy"
"Mail::DKIM::Canonicalization::Base"
"Mail::DKIM::Canonicalization::DkCommon"
"Mail::DKIM::Canonicalization::DkimCommon"
"Mail::DKIM::Canonicalization::dk_nofws"
"Mail::DKIM::Canonicalization::dk_simple"
"Mail::DKIM::Canonicalization::nowsp"
"Mail::DKIM::Canonicalization::relaxed"
"Mail::DKIM::Canonicalization::simple" "Mail::DKIM::Common"
"Mail::DKIM::DNS" "Mail::DKIM::DkPolicy" "Mail::DKIM::DkSignature"
"Mail::DKIM::DkimPolicy" "Mail::DKIM::Key" "Mail::DKIM::KeyValueList"
"Mail::DKIM::MessageParser" "Mail::DKIM::Policy" "Mail::DKIM::PrivateKey"
"Mail::DKIM::PublicKey" "Mail::DKIM::Signature" "Mail::DKIM::Signer"
"Mail::DKIM::SignerPolicy" "Mail::DKIM::TextWrap" "Mail::DKIM::Verifier"
"Mail::Field" "Mail::Field::AddrList" "Mail::Field::Date"
"Mail::Field::Generic" "Mail::Filter" "Mail::Header" "Mail::Internet"
"Mail::Mailer" "Mail::Mailer::qmail" "Mail::Mailer::rfc822"
"Mail::Mailer::sendmail" "Mail::Mailer::smtp" "Mail::Mailer::smtps"
"Mail::Mailer::testfile" "Mail::SPF" "Mail::SPF::Base"
"Mail::SPF::Exception" "Mail::SPF::MacroString" "Mail::SPF::Mech"
"Mail::SPF::Mech::A" "Mail::SPF::Mech::All" "Mail::SPF::Mech::Exists"
"Mail::SPF::Mech::IP4" "Mail::SPF::Mech::IP6" "Mail::SPF::Mech::Include"
"Mail::SPF::Mech::MX" "Mail::SPF::Mech::PTR" "Mail::SPF::Mod"
"Mail::SPF::Mod::Exp" "Mail::SPF::Mod::Redirect" "Mail::SPF::Record"
"Mail::SPF::Request" "Mail::SPF::Result" "Mail::SPF::SenderIPAddrMech"
"Mail::SPF::Server" "Mail::SPF::Term" "Mail::SPF::Util"
"Mail::SPF::v1::Record" "Mail::SPF::v2::Record" "Mail::Send"
"Mail::SpamAssassin" "Mail::SpamAssassin::AICache"
"Mail::SpamAssassin::ArchiveIterator" "Mail::SpamAssassin::AsyncLoop"
"Mail::SpamAssassin::AutoWhitelist" "Mail::SpamAssassin::Bayes"
"Mail::SpamAssassin::Bayes::CombineChi"
"Mail::SpamAssassin::Bayes::CombineNaiveBayes"
"Mail::SpamAssassin::BayesStore" "Mail::SpamAssassin::BayesStore::BDB"
"Mail::SpamAssassin::BayesStore::DBM"
"Mail::SpamAssassin::BayesStore::MySQL"
"Mail::SpamAssassin::BayesStore::PgSQL"
"Mail::SpamAssassin::BayesStore::SDBM"
"Mail::SpamAssassin::BayesStore::SQL" "Mail::SpamAssassin::Client"
"Mail::SpamAssassin::Conf" "Mail::SpamAssassin::Conf::LDAP"
"Mail::SpamAssassin::Conf::Parser" "Mail::SpamAssassin::Conf::SQL"
"Mail::SpamAssassin::Constants" "Mail::SpamAssassin::DBBasedAddrList"
"Mail::SpamAssassin::Dns" "Mail::SpamAssassin::DnsResolver"
"Mail::SpamAssassin::HTML" "Mail::SpamAssassin::Locales"
"Mail::SpamAssassin::Locker" "Mail::SpamAssassin::Locker::Flock"
"Mail::SpamAssassin::Locker::UnixNFSSafe"
"Mail::SpamAssassin::Locker::Win32" "Mail::SpamAssassin::Logger"
"Mail::SpamAssassin::Logger::File" "Mail::SpamAssassin::Logger::Stderr"
"Mail::SpamAssassin::Logger::Syslog" "Mail::SpamAssassin::MailingList"
"Mail::SpamAssassin::Message" "Mail::SpamAssassin::Message::Metadata"
"Mail::SpamAssassin::Message::Metadata::Received"
"Mail::SpamAssassin::Message::Node" "Mail::SpamAssassin::NetSet"
"Mail::SpamAssassin::PerMsgLearner" "Mail::SpamAssassin::PerMsgStatus"
"Mail::SpamAssassin::PersistentAddrList" "Mail::SpamAssassin::Plugin"
"Mail::SpamAssassin::Plugin::ASN" "Mail::SpamAssassin::Plugin::AWL"
"Mail::SpamAssassin::Plugin::AccessDB"
"Mail::SpamAssassin::Plugin::AntiVirus"
"Mail::SpamAssassin::Plugin::AutoLearnThreshold"
"Mail::SpamAssassin::Plugin::Bayes" "Mail::SpamAssassin::Plugin::BodyEval"
"Mail::SpamAssassin::Plugin::BodyRuleBaseExtractor"
"Mail::SpamAssassin::Plugin::Check" "Mail::SpamAssassin::Plugin::DCC"
"Mail::SpamAssassin::Plugin::DKIM" "Mail::SpamAssassin::Plugin::DNSEval"
"Mail::SpamAssassin::Plugin::FreeMail"
"Mail::SpamAssassin::Plugin::HTMLEval"
"Mail::SpamAssassin::Plugin::HTTPSMismatch"
"Mail::SpamAssassin::Plugin::Hashcash"
"Mail::SpamAssassin::Plugin::HeaderEval"
"Mail::SpamAssassin::Plugin::ImageInfo"
"Mail::SpamAssassin::Plugin::MIMEEval"
"Mail::SpamAssassin::Plugin::MIMEHeader"
"Mail::SpamAssassin::Plugin::OneLineBodyRuleType"
"Mail::SpamAssassin::Plugin::PhishTag" "Mail::SpamAssassin::Plugin::Pyzor"
"Mail::SpamAssassin::Plugin::Razor2"
"Mail::SpamAssassin::Plugin::RelayCountry"
"Mail::SpamAssassin::Plugin::RelayEval"
"Mail::SpamAssassin::Plugin::ReplaceTags"
"Mail::SpamAssassin::Plugin::Reuse"
"Mail::SpamAssassin::Plugin::Rule2XSBody" "Mail::SpamAssassin::Plugin::SPF"
"Mail::SpamAssassin::Plugin::Shortcircuit"
"Mail::SpamAssassin::Plugin::SpamCop" "Mail::SpamAssassin::Plugin::Test"
"Mail::SpamAssassin::Plugin::TextCat"
"Mail::SpamAssassin::Plugin::URIDNSBL"
"Mail::SpamAssassin::Plugin::URIDetail"
"Mail::SpamAssassin::Plugin::URIEval" "Mail::SpamAssassin::Plugin::VBounce"
"Mail::SpamAssassin::Plugin::WLBLEval"
"Mail::SpamAssassin::Plugin::WhiteListSubject"
"Mail::SpamAssassin::PluginHandler" "Mail::SpamAssassin::Reporter"
"Mail::SpamAssassin::SQLBasedAddrList"
"Mail::SpamAssassin::SpamdForkScaling"
"Mail::SpamAssassin::SubProcBackChannel" "Mail::SpamAssassin::Timeout"
"Mail::SpamAssassin::Util" "Mail::SpamAssassin::Util::DependencyInfo"
"Mail::SpamAssassin::Util::Progress"
"Mail::SpamAssassin::Util::RegistrarBoundaries"
"Mail::SpamAssassin::Util::ScopedTimer"
"Mail::SpamAssassin::Util::TieOneStringHash" "Mail::Util" "Math::BigFloat"
"Math::BigFloat::Trace" "Math::BigInt" "Math::BigInt::Calc"
"Math::BigInt::CalcEmu" "Math::BigInt::FastCalc" "Math::BigInt::Trace"
"Math::BigRat" "Math::Complex" "Math::Trig" "Memoize"
"Memoize::AnyDBM_File" "Memoize::Expire" "Memoize::ExpireFile"
"Memoize::ExpireTest" "Memoize::NDBM_File" "Memoize::SDBM_File"
"Memoize::Storable" "ModPerl::Const" "ModPerl::Global"
"ModPerl::MethodLookup" "ModPerl::PerlRun" "ModPerl::PerlRunPrefork"
"ModPerl::Registry" "ModPerl::RegistryBB" "ModPerl::RegistryCooker"
"ModPerl::RegistryLoader" "ModPerl::RegistryPrefork" "ModPerl::TestReport"
"ModPerl::Util" "Module::Pluggable" "Module::Pluggable::Object" "NDBM_File"
"NEXT" "Net::Cmd" "Net::Config" "Net::DNS" "Net::DNS::FAQ"
"Net::DNS::Header" "Net::DNS::Packet" "Net::DNS::Question" "Net::DNS::RR"
"Net::DNS::RR::A" "Net::DNS::RR::AAAA" "Net::DNS::RR::AFSDB"
"Net::DNS::RR::APL" "Net::DNS::RR::APL::ApItem" "Net::DNS::RR::CERT"
"Net::DNS::RR::CNAME" "Net::DNS::RR::DNAME" "Net::DNS::RR::EID"
"Net::DNS::RR::HINFO" "Net::DNS::RR::IPSECKEY" "Net::DNS::RR::ISDN"
"Net::DNS::RR::LOC" "Net::DNS::RR::MB" "Net::DNS::RR::MG"
"Net::DNS::RR::MINFO" "Net::DNS::RR::MR" "Net::DNS::RR::MX"
"Net::DNS::RR::NAPTR" "Net::DNS::RR::NIMLOC" "Net::DNS::RR::NS"
"Net::DNS::RR::NSAP" "Net::DNS::RR::NULL" "Net::DNS::RR::OPT"
"Net::DNS::RR::PTR" "Net::DNS::RR::PX" "Net::DNS::RR::RP"
"Net::DNS::RR::RT" "Net::DNS::RR::SOA" "Net::DNS::RR::SPF"
"Net::DNS::RR::SRV" "Net::DNS::RR::SSHFP" "Net::DNS::RR::TKEY"
"Net::DNS::RR::TSIG" "Net::DNS::RR::TXT" "Net::DNS::RR::Unknown"
"Net::DNS::RR::X25" "Net::DNS::Resolver" "Net::DNS::Resolver::Base"
"Net::DNS::Resolver::Recurse" "Net::DNS::Resolver::UNIX" "Net::DNS::Update"
"Net::Domain" "Net::FTP" "Net::FTP::A" "Net::FTP::E" "Net::FTP::I"
"Net::FTP::L" "Net::FTP::dataconn" "Net::HTTP" "Net::HTTP::Methods"
"Net::HTTP::NB" "Net::HTTPS" "Net::LibIDN" "Net::NNTP" "Net::Netrc"
"Net::POP3" "Net::Ping" "Net::SMTP" "Net::SMTP::SSL" "Net::SSLeay"
"Net::SSLeay::Handle" "Net::Time" "Net::hostent" "Net::libnetFAQ"
"Net::netent" "Net::protoent" "Net::servent" "NetAddr::IP"
"NetAddr::IP::Lite" "NetAddr::IP::Util" "NetAddr::IP::UtilPP"
"NetAddr::IP::Util_IS" "Newt" "O" "Opcode" "POSIX" "Package::Constants"
"Params::Validate" "Params::ValidatePP" "Params::ValidateXS" "PerlIO"
"PerlIO::encoding" "PerlIO::scalar" "PerlIO::via"
"PerlIO::via::QuotedPrint" "Perlilog" "Perlilog::PLerror"
"Perlilog::PLerrsys" "Pod::Checker" "Pod::Escapes" "Pod::Find"
"Pod::Functions" "Pod::Html" "Pod::InputObjects" "Pod::LaTeX" "Pod::Man"
"Pod::ParseLink" "Pod::ParseUtils" "Pod::Parser" "Pod::Perldoc"
"Pod::Perldoc::BaseTo" "Pod::Perldoc::GetOptsOO" "Pod::Perldoc::ToChecker"
"Pod::Perldoc::ToMan" "Pod::Perldoc::ToNroff" "Pod::Perldoc::ToPod"
"Pod::Perldoc::ToRtf" "Pod::Perldoc::ToText" "Pod::Perldoc::ToTk"
"Pod::Perldoc::ToXml" "Pod::PlainText" "Pod::Plainer" "Pod::Select"
"Pod::Simple" "Pod::Simple::BlackBox" "Pod::Simple::Checker"
"Pod::Simple::Debug" "Pod::Simple::DumpAsText" "Pod::Simple::DumpAsXML"
"Pod::Simple::HTML" "Pod::Simple::HTMLBatch" "Pod::Simple::HTMLLegacy"
"Pod::Simple::LinkSection" "Pod::Simple::Methody" "Pod::Simple::Progress"
"Pod::Simple::PullParser" "Pod::Simple::PullParserEndToken"
"Pod::Simple::PullParserStartToken" "Pod::Simple::PullParserTextToken"
"Pod::Simple::PullParserToken" "Pod::Simple::RTF" "Pod::Simple::Search"
"Pod::Simple::SimpleTree" "Pod::Simple::Subclassing" "Pod::Simple::Text"
"Pod::Simple::TextContent" "Pod::Simple::TiedOutFH"
"Pod::Simple::Transcode" "Pod::Simple::TranscodeDumb"
"Pod::Simple::TranscodeSmart" "Pod::Simple::XHTML"
"Pod::Simple::XMLOutStream" "Pod::Text" "Pod::Text::Color"
"Pod::Text::Overstrike" "Pod::Text::Termcap" "Pod::Usage" "Roadmap"
"SDBM_File" "SGMLS" "SGMLS::Output" "SGMLS::Refs" "SVN::Base" "SVN::Client"
"SVN::Core" "SVN::Delta" "SVN::Fs" "SVN::Ra" "SVN::Repos" "SVN::Wc" "Safe"
"Scalar::Util" "Scalar::Util::PP" "Search::Dict" "SelectSaver" "SelfLoader"
"Shell" "Socket" "Socket6" "Storable" "Switch" "Symbol" "Sys::Hostname"
"Sys::Syslog" "TAP::Base" "TAP::Formatter::Base" "TAP::Formatter::Color"
"TAP::Formatter::Console" "TAP::Formatter::Console::ParallelSession"
"TAP::Formatter::Console::Session" "TAP::Formatter::File"
"TAP::Formatter::File::Session" "TAP::Formatter::Session" "TAP::Harness"
"TAP::Object" "TAP::Parser" "TAP::Parser::Aggregator"
"TAP::Parser::Grammar" "TAP::Parser::Iterator"
"TAP::Parser::Iterator::Array" "TAP::Parser::Iterator::Process"
"TAP::Parser::Iterator::Stream" "TAP::Parser::IteratorFactory"
"TAP::Parser::Multiplexer" "TAP::Parser::Result"
"TAP::Parser::Result::Bailout" "TAP::Parser::Result::Comment"
"TAP::Parser::Result::Plan" "TAP::Parser::Result::Pragma"
"TAP::Parser::Result::Test" "TAP::Parser::Result::Unknown"
"TAP::Parser::Result::Version" "TAP::Parser::Result::YAML"
"TAP::Parser::ResultFactory" "TAP::Parser::Scheduler"
"TAP::Parser::Scheduler::Job" "TAP::Parser::Scheduler::Spinner"
"TAP::Parser::Source" "TAP::Parser::Source::Perl" "TAP::Parser::Utils"
"TAP::Parser::YAMLish::Reader" "TAP::Parser::YAMLish::Writer" "TASKS"
"Term::ANSIColor" "Term::Cap" "Term::Complete" "Term::ReadKey"
"Term::ReadLine" "Test" "Test::Harness" "Text::Abbrev" "Text::Balanced"
"Text::ParseWords" "Text::Soundex" "Text::Tabs" "Text::Wrap" "Thread"
"Thread::Queue" "Thread::Semaphore" "Tie::Array" "Tie::File" "Tie::Handle"
"Tie::Hash" "Tie::Hash::NamedCapture" "Tie::Memoize" "Tie::RefHash"
"Tie::Scalar" "Tie::StdHandle" "Tie::SubstrHash" "Time::CTime"
"Time::DaysInMonth" "Time::HiRes" "Time::JulianDay" "Time::Local"
"Time::ParseDate" "Time::Timezone" "Time::Zone" "Time::gmtime"
"Time::localtime" "Time::tm" "UNIVERSAL" "URI" "URI::Escape"
"URI::Heuristic" "URI::IRI" "URI::QueryParam" "URI::Split" "URI::URL"
"URI::WithBase" "URI::_foreign" "URI::_generic" "URI::_idna" "URI::_ldap"
"URI::_login" "URI::_punycode" "URI::_query" "URI::_segment" "URI::_server"
"URI::_userpass" "URI::data" "URI::file" "URI::file::Base" "URI::file::FAT"
"URI::file::Mac" "URI::file::OS2" "URI::file::QNX" "URI::file::Unix"
"URI::file::Win32" "URI::ftp" "URI::gopher" "URI::http" "URI::https"
"URI::ldap" "URI::ldapi" "URI::ldaps" "URI::mailto" "URI::mms" "URI::news"
"URI::nntp" "URI::pop" "URI::rlogin" "URI::rsync" "URI::rtsp" "URI::rtspu"
"URI::sip" "URI::sips" "URI::snews" "URI::ssh" "URI::telnet" "URI::tn3270"
"URI::urn" "URI::urn::isbn" "URI::urn::oid" "Unicode::Collate"
"Unicode::Normalize" "Unicode::UCD" "User::grent" "User::pwent"
"WWW::RobotRules" "WWW::RobotRules::AnyDBM_File" "XML::DOM"
"XML::DOM::AttDef" "XML::DOM::AttlistDecl" "XML::DOM::Attr"
"XML::DOM::CDATASection" "XML::DOM::CharacterData" "XML::DOM::Comment"
"XML::DOM::DOMException" "XML::DOM::DOMImplementation" "XML::DOM::Document"
"XML::DOM::DocumentFragment" "XML::DOM::DocumentType" "XML::DOM::Element"
"XML::DOM::ElementDecl" "XML::DOM::Entity" "XML::DOM::EntityReference"
"XML::DOM::NamedNodeMap" "XML::DOM::Node" "XML::DOM::NodeList"
"XML::DOM::Notation" "XML::DOM::Parser" "XML::DOM::PerlSAX"
"XML::DOM::ProcessingInstruction" "XML::DOM::Text" "XML::DOM::XMLDecl"
"XML::Handler::BuildDOM" "XML::Parser" "XML::Parser::Expat"
"XML::Parser::Style::Debug" "XML::Parser::Style::Objects"
"XML::Parser::Style::Stream" "XML::Parser::Style::Subs"
"XML::Parser::Style::Tree" "XML::RSS" "XML::RSS::Private::Output::Base"
"XML::RSS::Private::Output::Roles::ImageDims"
"XML::RSS::Private::Output::Roles::ModulesElems"
"XML::RSS::Private::Output::V0_9" "XML::RSS::Private::Output::V0_91"
"XML::RSS::Private::Output::V1_0" "XML::RSS::Private::Output::V2_0"
"XML::RegExp" "XSLoader" "a2p" "attributes" "autodie" "autodie::exception"
"autodie::exception::system" "autodie::hints" "autouse" "base" "bigint"
"bignum" "bigrat" "blib" "bytes" "charnames" "constant" "deprecate"
"diagnostics" "encoding" "encoding::warnings" "feature" "fields" "filetest"
"if" "integer" "less" "lib" "locale" "lwpcook" "lwptut" "mod_perl2" "mro"
"open.pod" "ops" "overload" "overload::numbers" "overloading" "perl"
"perl5004delta" "perl5005delta" "perl5100delta" "perl5101delta"
"perl5110delta" "perl5111delta" "perl5112delta" "perl5113delta"
"perl5114delta" "perl5115delta" "perl5120delta" "perl5121delta"
"perl5122delta" "perl5123delta" "perl561delta" "perl56delta" "perl570delta"
"perl571delta" "perl572delta" "perl573delta" "perl581delta" "perl582delta"
"perl583delta" "perl584delta" "perl585delta" "perl586delta" "perl587delta"
"perl588delta" "perl589delta" "perl58delta" "perl590delta" "perl591delta"
"perl592delta" "perl593delta" "perl594delta" "perl595delta" "perlaix"
"perlamiga" "perlapi" "perlapio" "perlapollo" "perlartistic" "perlbeos"
"perlbook" "perlboot" "perlbot" "perlbs2000" "perlcall" "perlce"
"perlcheat" "perlclib" "perlcn" "perlcommunity" "perlcompile" "perlcygwin"
"perldata" "perldbmfilter" "perldebguts" "perldebtut" "perldebug"
"perldelta" "perldgux" "perldiag" "perldoc" "perldos" "perldsc"
"perlebcdic" "perlembed" "perlepoc" "perlfaq" "perlfaq1" "perlfaq2"
"perlfaq3" "perlfaq4" "perlfaq5" "perlfaq6" "perlfaq7" "perlfaq8"
"perlfaq9" "perlfilter" "perlfork" "perlform" "perlfreebsd" "perlfunc"
"perlglossary" "perlgpl" "perlguts" "perlhack" "perlhaiku" "perlhist"
"perlhpux" "perlhurd" "perlintern" "perlintro" "perliol" "perlipc"
"perlirix" "perljp" "perlko" "perllexwarn" "perllinux" "perllocale"
"perllol" "perlmacos" "perlmacosx" "perlmod" "perlmodinstall" "perlmodlib"
"perlmodstyle" "perlmpeix" "perlmroapi" "perlnetware" "perlnewmod"
"perlnumber" "perlobj" "perlop" "perlopenbsd" "perlopentut" "perlos2"
"perlos390" "perlos400" "perlpacktut" "perlperf" "perlplan9" "perlpod"
"perlpodspec" "perlpolicy" "perlport" "perlpragma" "perlqnx" "perlre"
"perlreapi" "perlrebackslash" "perlrecharclass" "perlref" "perlreftut"
"perlreguts" "perlrepository" "perlrequick" "perlreref" "perlretut"
"perlriscos" "perlrun" "perlsec" "perlsolaris" "perlstyle" "perlsub"
"perlsymbian" "perlsyn" "perlthrtut" "perltie" "perltoc" "perltodo"
"perltooc" "perltoot" "perltrap" "perltru64" "perltw" "perlunicode"
"perlunifaq" "perluniintro" "perluniprops" "perlunitut" "perlutil"
"perluts" "perlvar" "perlvmesa" "perlvms" "perlvos" "perlwin32" "perlxs"
"perlxstut" "re" "sigtrap" "sort.pod" "spamassassin-run" "strict" "subs"
"threads" "threads::shared" "utf8" "vars" "version" "version::Internals"
"version::vxs" "vmsish" "warnings" "warnings::register"))
